[[shades]]
name = ".config/hypr/shaders/blue-light-filter.glsl.mustache"
start_time = 19:00:00

[[shades]]
name = ".config/hypr/shaders/gray.glsl.mustache"
start_time = 22:00:00
end_time = 06:00:00   # optional if more than one shader has start_time
