
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░

exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE
exec = hyprshade auto

#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
     kb_layout = gb, es, gr
    # follow_mouse = 1
     sensitivity = 3
    # force_no_accel = 0
    # accel_profile = flat 
     numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }

}

general {
    gaps_in = 2
    gaps_out = 0
}

decoration {
    rounding = 0
    rounding_power = 0
}

# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
} 



# exec = hyprshade auto
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE
cursor:no_hardware_cursors = 1
# render:explicit_sync = 0
