################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,1920x1080@60,1
monitor = eDP-1, 1920x1080@60, 0x0, 1
monitor = sunshine_1, 1920x1080@60, 0x-1080, 1
# monitor = HDMI-A-1, 1920x1080@60, 0x1080, 1
monitor = HDMI-A-1, 1920x1080@60, auto, 1, mirror, eDP-1

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

workspace=1,layoutopt:wslayout-layout:master #workspace id
workspace=2,layoutopt:wslayout-layout:master #workspace id
workspace=3,layoutopt:wslayout-layout:master #workspace id

workspace=4,layoutopt:wslayout-layout:dwindle 

workspace=5,layoutopt:wslayout-layout:master #workspace id
workspace=6,layoutopt:wslayout-layout:master #workspace id
workspace=7,layoutopt:wslayout-layout:master #workspace id
workspace=8,layoutopt:wslayout-layout:master #workspace id
workspace=9,layoutopt:wslayout-layout:master #workspace id
workspace=10,layoutopt:wslayout-layout:master #workspace id
# Example windowrule

windowrule = opacity 1 override 1 override 1 override,class:.+

windowrule = opacity 0.9 0.75 ,class:^(com.mitchellh.ghostty)$

windowrule = float, class:^(org.pulseaudio.pavucontrol)$

windowrule = float, class:^(blueman-manager)$
windowrule = workspace 10, class:^(wasistlos)$
windowrule = workspace 2, class:^(firefox)$
windowrule = workspace 1, class:^(com.github.flxzt.rnote)$
windowrule = workspace 9, class:^(Spotify)$
windowrule = workspace 4, class:^(python3)$
windowrule = workspace 4, class:^(Matplotlib)$
windowrule = workspace 4, class:^(matplotlib)$

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 10,monitor:HDMI-A-1
workspace = 10,monitor:sunshine_1

windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
windowrule = nofocus, class:^(xwaylandvideobridge)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
