
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

$&=override

input:tablet {
  output = HDMI-A-1
}

# Workspace Assignment
windowrule = workspace 1, match:class ^(cs2)$
windowrule = workspace 3, match:class ^(firefox)$
windowrule = workspace 10, match:class ^(anki)$
windowrule = workspace 10, match:class ^(com.moonlight_stream.Moonlight)$
windowrule = float on, size 620 400 ,match:class ^(anki)$, match:title (Add)
windowrule = float on, size 460 900, match:title ^(Friends List)$
windowrule = center on, match:initial_title ^(Sign in to Steam)$
windowrule = float on, match:class [Ss]team ,match:title negative:(Steam)
windowrule = workspace 2 silent, center on, match:class ^([Dd]iscord|discord-stable|[Ss]team|heroic)$
windowrule = workspace 2, match:class ^(org.pwmt.zathura)$

windowrule = workspace 2 silent, match:class ^(wasistlos|org.mozilla.Thunderbird|python3|Matplotlib|matplotlib)$
windowrule = workspace 10, match:class ^(alvr.dashboard)$
windowrule = workspace 10 silent, match:class ^(localsend)$
windowrule = workspace 4, match:class ^([Ss]potify)$
# windowrule = workspace special, match:class ^(com.vixalien.sticky)$
windowrule = fullscreen on, match:class ^(hl2_linux)$

# Floating Rules
windowrule = float on, size 400 400, match:title ^(Sticky Note)$
windowrule = float on, size 700 500, match:title ^(Volume Control)$
windowrule = float on, match:class anki ,match:title negative:(User 1 - Anki)
windowrule = float on, size 500 300, match:class org.inkscape.Inkscape ,match:title negative:(New document 1 - Inkscape)


# Rule to make Inkscape windows float and have a specific size
# windowrulev2 = float on, size 600 400, match:class ^(org.inkscape.Inkscape)$
# windowrulev2 = center on, match:class:^(org.inkscape.Inkscape)$

# Optional: If you want the FIRST window to be tiled but others to float,
# you would normally need a script, but you can "pin" the behavior like this:
# windowrulev2 = tile, class:^(org.inkscape.Inkscape)$, title:^(.*Drawing 1.*)

# Opacity 
windowrule = opacity 1 override 1 override 1, match:class .*

windowrule = opacity 0.95 0.85 1, match:initial_class ^(kitty)$
# windowrule = opacity 1 override 1 override 1, match:title ^(Spotify Free|Spotify Premium)$

# Misc
windowrule = idle_inhibit fullscreen, match:class ^(.*celluloid.*|.*mpv.*|.*vlc.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*[Ss]potify.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*LibreWolf.*|.*floorp.*|.*Brave.*|.*firefox.*|.*chromium.*|.*zen.*|.*vivaldi.*)$

windowrule = float on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = keep_aspect_ratio on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = move 73% 72%, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = size 25% 25%, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = pin on, match:title ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture|Library)$
windowrule = float on, match:title ^(About Mozilla Firefox)$

windowrule = float on, match:title ^(Open|Authentication Required|Add Folder to Workspace|Choose Files|Save As|Confirm to replace files|File Operation Progress|File Upload|Choose wallpaper|Library)(.*)$
windowrule = float on, match:class ^([Xx]dg-desktop-portal-gtk|.*dialog.*)$
windowrule = float on, match:title ^(.*dialog.*)$

